CREATE TABLE IF NOT EXISTS `company_lead` (
  `lead_id` bigint NOT NULL AUTO_INCREMENT,
  `source_id` bigint NULL DEFAULT NULL,
  `source_name` varchar(100) NOT NULL,
  `source_url` varchar(500) NOT NULL,
  `source_title` varchar(255) NULL DEFAULT NULL,
  `source_type` varchar(50) NOT NULL DEFAULT 'PUBLIC',
  `company_name` varchar(200) NOT NULL,
  `lead_title` varchar(255) NOT NULL,
  `summary` text NULL,
  `demand_type` varchar(50) NOT NULL DEFAULT 'UNKNOWN',
  `confidence_score` int NOT NULL DEFAULT 0,
  `confidence_level` varchar(20) NOT NULL DEFAULT 'LOW',
  `industry_name` varchar(100) NULL DEFAULT NULL,
  `region_province` varchar(100) NULL DEFAULT NULL,
  `region_city` varchar(100) NULL DEFAULT NULL,
  `region_district` varchar(100) NULL DEFAULT NULL,
  `hit_keywords` text NULL,
  `evidence_count` int NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'NEW',
  `owner_user_id` int NULL DEFAULT NULL,
  `invalid_reason` varchar(255) NULL DEFAULT NULL,
  `remark` text NULL,
  `dedupe_key` varchar(191) NOT NULL,
  `converted_radar_lead_id` bigint NULL DEFAULT NULL,
  `converted_at` datetime(3) NULL DEFAULT NULL,
  `first_seen_at` datetime(3) NULL DEFAULT NULL,
  `last_seen_at` datetime(3) NULL DEFAULT NULL,
  `crawled_at` datetime(3) NULL DEFAULT NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (`lead_id`),
  UNIQUE KEY `company_lead_dedupe_key_uq` (`dedupe_key`),
  KEY `company_lead_company_name_idx` (`company_name`),
  KEY `company_lead_status_idx` (`status`),
  KEY `company_lead_source_name_idx` (`source_name`),
  KEY `company_lead_converted_radar_lead_id_idx` (`converted_radar_lead_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `lead_evidence` (
  `evidence_id` bigint NOT NULL AUTO_INCREMENT,
  `lead_id` bigint NOT NULL,
  `evidence_type` varchar(50) NOT NULL,
  `source_title` varchar(255) NULL DEFAULT NULL,
  `source_link` varchar(500) NOT NULL,
  `raw_text` text NULL,
  `matched_keywords` text NULL,
  `matched_sentences` text NULL,
  `score_delta` int NOT NULL DEFAULT 0,
  `content_hash` varchar(80) NOT NULL,
  `published_at` datetime(3) NULL DEFAULT NULL,
  `crawled_at` datetime(3) NULL DEFAULT NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (`evidence_id`),
  UNIQUE KEY `lead_evidence_lead_hash_uq` (`lead_id`, `content_hash`),
  KEY `lead_evidence_lead_id_idx` (`lead_id`),
  KEY `lead_evidence_type_idx` (`evidence_type`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
