CREATE TABLE IF NOT EXISTS `crawler_task_item` (
  `item_id` bigint NOT NULL AUTO_INCREMENT,
  `source_id` bigint NOT NULL,
  `last_task_id` bigint NULL DEFAULT NULL,
  `source_ref_type` varchar(50) NULL DEFAULT NULL,
  `source_ref_id` bigint NULL DEFAULT NULL,
  `source_url` varchar(800) NOT NULL,
  `url_hash` varchar(80) NOT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'PENDING',
  `retry_count` int NOT NULL DEFAULT 0,
  `max_retry_count` int NOT NULL DEFAULT 3,
  `next_retry_at` datetime(3) NULL DEFAULT NULL,
  `last_http_status` int NULL DEFAULT NULL,
  `last_error` text NULL,
  `skip_reason` varchar(255) NULL DEFAULT NULL,
  `published_at` datetime(3) NULL DEFAULT NULL,
  `last_started_at` datetime(3) NULL DEFAULT NULL,
  `last_finished_at` datetime(3) NULL DEFAULT NULL,
  `last_success_at` datetime(3) NULL DEFAULT NULL,
  `response_hash` varchar(80) NULL DEFAULT NULL,
  `parsed_payload_json` text NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`item_id`),
  UNIQUE KEY `crawler_task_item_source_url_uq` (`source_id`, `url_hash`),
  KEY `crawler_task_item_last_task_id_idx` (`last_task_id`),
  KEY `crawler_task_item_source_status_idx` (`source_id`, `status`),
  KEY `crawler_task_item_next_retry_idx` (`next_retry_at`),
  KEY `crawler_task_item_source_ref_idx` (`source_ref_type`, `source_ref_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
