CREATE TABLE IF NOT EXISTS `signal_event` (
  `event_id` bigint NOT NULL AUTO_INCREMENT,
  `enterprise_id` bigint NULL DEFAULT NULL,
  `company_name` varchar(200) NOT NULL,
  `event_type` varchar(50) NOT NULL,
  `event_title` varchar(255) NOT NULL,
  `event_summary` text NULL,
  `event_time` datetime(3) NULL DEFAULT NULL,
  `source_type` varchar(50) NOT NULL,
  `source_name` varchar(100) NOT NULL,
  `source_url` varchar(500) NOT NULL,
  `confidence_score` int NOT NULL DEFAULT 0,
  `status` varchar(30) NOT NULL DEFAULT 'NEW',
  `related_external_lead_id` bigint NULL DEFAULT NULL,
  `related_radar_lead_id` bigint NULL DEFAULT NULL,
  `content_hash` varchar(80) NOT NULL,
  `raw_payload_json` text NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (`event_id`),
  UNIQUE KEY `signal_event_content_hash_uq` (`content_hash`),
  KEY `signal_event_company_name_idx` (`company_name`),
  KEY `signal_event_event_type_idx` (`event_type`),
  KEY `signal_event_status_idx` (`status`),
  KEY `signal_event_source_type_idx` (`source_type`),
  KEY `signal_event_external_lead_idx` (`related_external_lead_id`),
  KEY `signal_event_radar_lead_idx` (`related_radar_lead_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `signal_evidence` (
  `evidence_id` bigint NOT NULL AUTO_INCREMENT,
  `event_id` bigint NOT NULL,
  `evidence_type` varchar(50) NOT NULL,
  `source_title` varchar(255) NULL DEFAULT NULL,
  `source_link` varchar(500) NOT NULL,
  `raw_text` text NULL,
  `matched_keywords_json` text NULL,
  `matched_sentences_json` text NULL,
  `score_delta` int NOT NULL DEFAULT 0,
  `content_hash` varchar(80) NOT NULL,
  `published_at` datetime(3) NULL DEFAULT NULL,
  `crawled_at` datetime(3) NULL DEFAULT NULL,
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (`evidence_id`),
  UNIQUE KEY `signal_evidence_event_hash_uq` (`event_id`, `content_hash`),
  KEY `signal_evidence_event_id_idx` (`event_id`),
  KEY `signal_evidence_content_hash_idx` (`content_hash`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
