services:                                                                                                                                                                                                                                                                                   
  mysql:                                                                                                                                                                                                                                   
    image: mysql:8.0                                                                                                                                                                                                                 
    ports:                                                                                                                                                                                                                                 
      - '3306:3306'
    networks:
      - magic-network
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: magic # 可选，创建一个初始数据库
    volumes:
      - mysql_data:/var/lib/mysql                                                                                                                                                                                                          
      - ./sql/magic.sql:/docker-entrypoint-initdb.d/init.sql # 挂载 SQL 文件
    # command: --init-file=/docker-entrypoint-initdb.d/init.sql # 指定初始化文件
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./dist:/usr/share/nginx/html
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on: # 添加 depends_on 确保 node 服务先启动（如果 nginx 需要代理 node）
  #     - node
  #     - mysql
  #   networks:
  #     - magic-network
  node:
    image: node:22.14.0
    ports:
      - '5320:5320'
    volumes:
      - ./node:/app
    working_dir: /app
    environment: # 使用 environment 设置环境变量
      - PORT=5320
    command: node ./server/index.mjs
    depends_on:
      - mysql
    networks:
      - magic-network

networks:
  magic-network:
    name: magic-network

volumes:
  mysql_data:
